project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /src/i18n/strings.ftl
    dest: /ReactNative/strings.ftl
    # Note: this uses the Crowdin locale which always has a region. We need to
    # mess with this later in i18ncli
    translation: /src/i18n/l10n/%locale%.ftl
    type: ftl
  - source: /ios/InfoPlist.xcstrings
    dest: /ReactNative/InfoPlist.xcstrings
    translation: /ios/InfoPlist.xcstrings
    multilingual: true
    # iOS strings for AppStore
    # Note: this uses the Crowdin osx-locale
  - source: /fastlane/metadata/ios/default/description.txt
    dest: /ReactNative/metadata/ios/description.txt
    translation: /fastlane/metadata/%osx_locale%/description.txt
  - source: /fastlane/metadata/ios/default/keywords.txt
    dest: /ReactNative/metadata/ios/keywords.txt
    translation: /fastlane/metadata/%osx_locale%/keywords.txt
  # - source: /fastlane/metadata/ios/default/name.txt
  #   dest: /ReactNative/metadata/ios/name.txt
  #   translation: /fastlane/metadata/%osx_locale%/name.txt
  - source: /fastlane/metadata/ios/default/promotional_text.txt
    dest: /ReactNative/metadata/ios/promotional_text.txt
    translation: /fastlane/metadata/%osx_locale%/promotional_text.txt
  - source: /fastlane/metadata/ios/default/subtitle.txt
    dest: /ReactNative/metadata/ios/subtitle.txt
    translation: /fastlane/metadata/%osx_locale%/subtitle.txt


