##
# Run tests
##
name: Tests
on:
  pull_request:
  push:

jobs:
  # Seemed to stop working on 20220106, see https://github.com/fkirc/skip-duplicate-actions/issues/127
  # pre_build:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - uses: fkirc/skip-duplicate-actions@master
  #       with:
  #         github_token: ${{ github.token }}
  #         cancel_others: true

  test:
    name: Run Tests
    needs: pre_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test

  notify:
    name: Notify Slack
    needs: test
    if: ${{ success() || failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: iRoachie/slack-github-actions@v2.0.1
        if: env.SLACK_WEBHOOK_URL != null
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BUILDS_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
