##
# Run unit test and the action itself
##
name: Unit Test
on:
  pull_request:
  push:
    branches:
      - main
      - feature/**

jobs:
  # unit tests
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - uses: ./
      with:
        milliseconds: 1000