##
# Run fbt to collect new text wrapped in <fbt> tags for translation
# Merge PRs from Crowdin
# Generate a single translation file after PR merged
# Convert the translation output into an Android string resource file
##
name: Integrate Crowdin Translations

# https://brennerm.github.io/posts/trigger-github-actions-on-pr-close.html
# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  collect-translation-files:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run manifest
  collect-translation-strings:
    needs: collect-translation-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run collect-fbts
    

    